branches:
  - main
  - name: next
    channel: next
    prerelease: next
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      parserOpts:
        headerPattern: '^(\w*)(?:\((.*)\))?!?: (.*)$'
        breakingHeaderPattern: '^(\w*)(?:\((.*)\))?!: (.*)$'
      releaseRules:
        - breaking: true
          release: major
        - revert: true
          release: patch
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: perf
          release: patch
        - type: build
          scope: deps
          release: patch
        - type: build
          scope: peer-deps
          release: patch
        - type: build
          scope: release-patch
          release: patch
        - type: build
          scope: release-minor
          release: minor
        - type: build
          scope: release-major
          release: major
  - - "@semantic-release/release-notes-generator"
    - preset: angular
      parserOpts:
        headerPattern: '^(\w*)(?:\((.*)\))?!?: (.*)$'
        breakingHeaderPattern: '^(\w*)(?:\((.*)\))?!: (.*)$'
  - - "@semantic-release/changelog"
    - changelogTitle: "# Changelog

        All notable changes to this project will be documented in this file. Dates are displayed in UTC."
  - - "semantic-release-replace-plugin"
    - replacements:
        - files:
            - "./lib/**/*"
          from: "\\$\\{__VERSION__\\}"
          to: "${nextRelease.version}"
          results:
            - file: "./lib/classic.cjs"
              hasChanged: true
              numMatches: 1
              numReplacements: 1
            - file: "./lib/classic.d.cts"
              hasChanged: false
              numMatches: 0
              numReplacements: 0
            - file: "./lib/classic.d.mts"
              hasChanged: false
              numMatches: 0
              numReplacements: 0
            - file: "./lib/classic.mjs"
              hasChanged: true
              numMatches: 1
              numReplacements: 1
            - file: "./lib/flat.cjs"
              hasChanged: true
              numMatches: 1
              numReplacements: 1
            - file: "./lib/flat.d.cts"
              hasChanged: false
              numMatches: 0
              numReplacements: 0
            - file: "./lib/flat.d.mts"
              hasChanged: false
              numMatches: 0
              numReplacements: 0
            - file: "./lib/flat.mjs"
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
  - "@semantic-release/npm"
  - - "@semantic-release/github"
    - releasedLabels:
        - "<%= nextRelease.channel === 'next' ? 'Status: Beta Released' : 'Status: Released' %>"
